---
output: github_document
---


```{r setup, include=FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  warning = FALSE,
  erro = FALSE,
  message = FALSE,
  comment = "#>"
)
```



# 


## **Loading internal functions**

```{r,results='hide'}
functions_files <- list.files('r/functions/',full.names = T)
purrr::map(functions_files,source)
#webshot::install_phantomjs(force=TRUE)
```



## **XCO2 download and pre-processing**

### **Download**
```{r}
# url_filename <- list.files("url/",
#                             pattern = ".txt",
#                             full.names = TRUE)
# 
# urls <- read.table(url_filename) |>
#   dplyr::filter(!stringr::str_detect(V1,".pdf"))
# n_urls <- nrow(urls)
# 
# ### Download
# tictoc::tic()
# furrr::future_pmap(list(urls[,1],"input your user","your password"),my_ncdf4_download)
# tictoc::toc()
```

### **Extraction**

```{r}
# files_names <- list.files("data-raw/",
#                           pattern = "nc",
#                           full.names = TRUE)
# 
# #### Extracting
# 
# xco2 <- purrr::map_df(files_names, my_ncdf4_extractor) |>
#   dplyr::mutate(
#     date = as.Date.POSIXct(time)
#   )
# dplyr::glimpse(xco2)

# ### Saving full data

# readr::write_rds(xco2,'data/xco2_full.rds')
```


### **Aggregation**

```{r}
# Expand grid for brazil
#
##
# dist <- 0.5
# grid_br <- expand.grid(lon=seq(-74,
#                                -27,dist),
#                        lat=seq(-34,
#                                6,
#                                dist))
# plot(grid_br)
# 
# 
# br <- geobr::read_country(showProgress = FALSE)
# region <- geobr::read_region(showProgress = FALSE)
# 
# pol_br <- br$geom |> purrr::pluck(1) |> as.matrix()
# pol_north <- region$geom |> purrr::pluck(1) |> as.matrix()
# pol_northeast <- region$geom |> purrr::pluck(2) |> as.matrix()
# pol_southeast <- region$geom |> purrr::pluck(3) |> as.matrix()
# pol_south <- region$geom |> purrr::pluck(4) |> as.matrix()
# pol_midwest<- region$geom |> purrr::pluck(5) |> as.matrix()
# 
# # correcting poligions
# 
# pol_br <- pol_br[pol_br[,1]<=-34,]
# pol_br <- pol_br[!((pol_br[,1]>=-38.8 & pol_br[,1]<=-38.6) &
#                      (pol_br[,2]>= -19 & pol_br[,2]<= -16)),]
# 
# pol_northeast <- pol_northeast[pol_northeast[,1]<=-34,]
# pol_northeast <- pol_northeast[!((pol_northeast[,1]>=-38.7 &
#                                     pol_northeast[,1]<=-38.6) &
#                                    pol_northeast[,2]<= -15),]
# 
# pol_southeast <- pol_southeast[pol_southeast[,1]<=-30,]
# 
# 
# ### filtering expanded grid to the brazil boundries
# 
# grid_br_cut <- grid_br |>
#   dplyr::mutate(
#     flag_br = def_pol(lon,lat,pol_br),
#     flag_north = def_pol(lon,lat,pol_north),
#     flag_northeast = def_pol(lon,lat,pol_northeast),
#     flag_midwest= def_pol(lon,lat,pol_midwest),
#     flag_southeast = def_pol(lon,lat,pol_southeast),
#     flag_south = def_pol(lon,lat,pol_south)
#   ) |>
#   tidyr::pivot_longer(
#     tidyr::starts_with('flag'),
#     names_to = 'region',
#     values_to = 'flag'
#   ) |>
#   dplyr::filter(flag) |>
#   dplyr::select(lon,lat) |>
#   dplyr::group_by(lon,lat) |>
#   dplyr::summarise(
#     n_obs = dplyr::n()
#   )
# 
# plot(grid_br_cut$lon,grid_br_cut$lat)
# 
# 
# #### aggregation
# xco2df <- readr::read_rds('data/xco2_full.rds')
# 
# xco2_full_trend <- xco2df |> dplyr::mutate(
#   year =lubridate::year(date),
#   month = lubridate::month(date)
# )
# 
# max(xco2_full_trend$year)
# 
# 
# for(i in 2015:2023){
#   aux_xco2 <- xco2_full_trend |>
#     dplyr::filter(year==i)
#   vct_xco2 <- vector();dist_xco2 <- vector();
#   lon_grid <- vector();lat_grid <- vector();
#   for(k in 1:nrow(aux_xco2)){
#     d <- sqrt((aux_xco2$lon[k]-grid_br_cut$lon)^2+
#                 (aux_xco2$lat[k]-grid_br_cut$lat)^2
#     )
#     min_index <- order(d)[1]
#     vct_xco2[k] <- aux_xco2$xco2[min_index]
#     dist_xco2[k] <- d[order(d)[1]]
#     lon_grid[k] <- grid_br_cut$lon[min_index]
#     lat_grid[k] <- grid_br_cut$lat[min_index]
#   }
#   aux_xco2$dist_xco2 <- dist_xco2
#   aux_xco2$xco2_new <- vct_xco2
#   aux_xco2$lon_grid <- lon_grid
#   aux_xco2$lat_grid <- lat_grid
#   if(i == 2015){
#     xco2_full_trend_cut <- aux_xco2
#   }else{
#     xco2_full_trend_cut <- rbind(xco2_full_trend_cut,aux_xco2)
#   }
# }
# 
# 
# xco2_full_trend_cut|>
#   dplyr::mutate(
#     dist_conf = sqrt((lon - lon_grid)^2 + (lat - lat_grid)^2)
#   ) |>
#   dplyr::glimpse()
# 
# nrow(xco2_full_trend_cut |>
#        dplyr::mutate(
#          dist_conf = sqrt((lon - lon_grid)^2 + (lat - lat_grid)^2),
#          dist_bol = dist_xco2 - dist_conf
#        ) |>
#        dplyr::filter(dist_bol ==0)) == nrow(xco2_full_trend_cut)
# 
# ### Saving aggregated data
# readr::write_rds(xco2_full_trend_cut,'data/xco2_0.5deg_full_trend.rds')

```


## **Loading data and shps**

```{r}
br <- geobr::read_country(showProgress = FALSE)
south_file <- list.files('South_America/',pattern = 'shp',full.names = T)
south_america <- sf::read_sf(south_file[1])
biomes <- geobr::read_biomes(showProgress = FALSE) 

xco2df <- readr::read_rds('data/xco2_0.5deg_full_trend.rds')
```


## **Data Overview**

###**Descriptive statistics** 

```{r}
df_stat_desc <- xco2df |>
  dplyr::filter(dist_xco2<0.25) |>
  dplyr::mutate(
    date = lubridate::make_date(year,month,'15')
  ) |>
  dplyr::group_by(date) |>
  dplyr::summarise(
    N = length(xco2),
    MIN = min(xco2),
    MEAN = mean(xco2),
    MEDIAN = median(xco2),
    MAX = max(xco2),
    VARIANCY  = var(xco2),
    STD_DV = sd(xco2),
    CV = 100*STD_DV/MEAN,
    SKW = agricolae::skewness(xco2),
    KRT = agricolae::kurtosis(xco2),
    )

dplyr::glimpse(df_stat_desc)
#DT::datatable(df_stat_desc)
```

### **Histograms**

```{r}
xco2df |>
  dplyr::filter(dist_xco2<0.25 & year <2023) |>
  ggplot2::ggplot(ggplot2::aes(x=xco2)) +
  ggplot2::geom_histogram(color="black",fill="gray",
                 bins = 30) +
  ggplot2::facet_wrap(~year, scales = "free") +
  ggplot2::theme_bw()
```



## **Temporal visualization**

### ***General for Brazil***
```{r}

xco2df |>
  dplyr::filter(dist_xco2<0.25) |> # radius (grid cell = 0.5°)
  dplyr::filter(year %in% 2015:2022) |>
  dplyr::group_by(year,date) |>
  dplyr::summarise(xco2_mean=mean(xco2)) |>
  ggplot2::ggplot(ggplot2::aes(x=date,y=xco2_mean))+
  ggplot2::geom_point(shape=21,color="black",fill="gray") +
  ggplot2::geom_line(color="red")+
  ggplot2::geom_smooth(method = "lm") +
  ggplot2::ylim(390,420)+
  ggpubr::stat_regline_equation(ggplot2::aes(
                                  label =  paste(..eq.label.., ..rr.label..,
                                                 sep = "*plain(\",\")~~")),
                                label.y = 420) +
  ggplot2::facet_wrap(~year,scales ='free')+
  ggplot2::theme_bw()+
  ggplot2::labs(x='',y=expression('Xco'[2]~' (ppm)'),fill='' )


# ggplot2::ggsave('img/xco2_temporal_ano.png',units="in", width=10, height=7,
#                 dpi=300)
```

### ***Rationality of beta***
```{r}
xco2df_rationality <- xco2df |>
  dplyr::filter(dist_xco2<0.25) |>
  dplyr::mutate(
    lon = lon_grid,
    lat = lat_grid,
  ) |>
  dplyr::filter(lon == -50, lat ==-19) |>
  dplyr::select(-c(lon_grid,lat_grid)) |>
  dplyr::group_by(lon,lat,year,month) |>
  dplyr::summarise(
    xco2_mean= mean(xco2,na.rm=TRUE),
    xco2_sd = sd(xco2,na.rm=TRUE),
    xco2_uncertanty = mean(uncertanty),
    nobs = dplyr::n(),
    xco2_ep = xco2_sd/sqrt(nobs),
    cv = 100*xco2_sd/xco2_mean
  ) |>
  dplyr::mutate(
    date = lubridate::make_date(year,month,'15')
  )
mod <- lm(xco2_mean~x,data =xco2df_rationality |>
            dplyr::mutate(
              x = 1:dplyr::n()
            ))
xco2df_rationality |>
  dplyr::filter(lubridate::year(date)<2023) |>
  dplyr::mutate(
    x=1:dplyr::n(),
    xco2_est = mod$coefficients[1] + mod$coefficients[2]*x,
    delta=xco2_est - xco2_mean,
    xco2r = (mod$coefficients[1]-delta)-(mean(xco2_mean)-mod$coefficients[1])
  ) |>
  dplyr::group_by(date) |>
  dplyr::summarise(xco2_mean=mean(xco2r)) |>
  ggplot2::ggplot(ggplot2::aes(x=date,y=xco2_mean )) +
  ggplot2::geom_point(shape=21,color="black",fill="gray") +
  ggplot2::geom_line(color="red") +
  ggplot2::geom_smooth(method = "lm") +
  ggpubr::stat_regline_equation(ggplot2::aes(
    label =  paste(..eq.label.., ..rr.label.., sep = "*plain(\",\")~~"))) +
  ggplot2::facet_wrap(~lubridate::year(date),scales = 'free_x')+
  ggplot2::theme_bw()+
  ggplot2::xlab('Month')+
  ggplot2::ylab(expression(
    'Xco'[2][R]~' (ppm)'
  ))

# ggplot2::ggsave('img/rationality_beta.png',units="in", width=8, height=6,
#                dpi=300)
```




## **Beta analisys and plots on a per-year basis by grid cell**

```{r}
for(i in 2015:2022){
  
  print("===============================================")
  
  print(i)
  
  print("===============================================")
  
  xco2df_filter <- xco2df |>
    dplyr::filter(year == i) |> ## filter by year
    dplyr::filter(dist_xco2<0.25) |>
    dplyr::mutate(
      lon = lon_grid,
      lat = lat_grid,
    ) |>
    dplyr::select(-c(lon_grid,lat_grid)) |>
    dplyr::group_by(lon,lat,year,month) |> ## data month and grid cell aggregation
    dplyr::summarise(
      xco2_mean= mean(xco2,na.rm=TRUE),
      xco2_sd = sd(xco2,na.rm=TRUE),
      xco2_uncertanty = mean(uncertanty),
      nobs = dplyr::n(),
      xco2_ep = xco2_sd/sqrt(nobs),
      cv = 100*xco2_sd/xco2_mean
    ) |>
    dplyr::mutate(
      date = lubridate::make_date(year,month,'15')
    )
  
  ### general model for the year
  
  mod <- lm(xco2_mean~x,data =xco2df_filter |>
              dplyr::mutate(
                x = 1:dplyr::n()
              ))
  
  print("----------------------------")
  print("XCO2 before regionalization")
  
  plot_1 <- xco2df_filter |>
    dplyr::group_by(date) |>
    dplyr::summarise(xco2_mean=mean(xco2_mean)) |>
    ggplot2::ggplot(ggplot2::aes(x=date,y=xco2_mean )) +
    ggplot2::geom_point(shape=21,color="black",fill="gray") +
    ggplot2::geom_line(color="red") +
    ggplot2::geom_smooth(method = "lm") +
    ggpubr::stat_regline_equation(ggplot2::aes(
      label =  paste(..eq.label.., ..rr.label.., sep = "*plain(\",\")~~"))) +
    ggplot2::theme_bw()+
    ggplot2::xlab('Date')+
    ggplot2::ylab(expression(
      'Xco'[2]~' (ppm)'
    ))
  print(plot_1)
  
  #### regionalization of XCO2 
  print("----------------------------")
  print("XCO2 after regionalization")
  
  plot_2 <- xco2df_filter |>
    dplyr::mutate(
      x=1:dplyr::n(),
      xco2_est = mod$coefficients[1] + mod$coefficients[2]*x,
      delta=xco2_est - xco2_mean,
      xco2r = (mod$coefficients[1]-delta)-(mean(xco2_mean)-mod$coefficients[1])
    ) |>
    dplyr::group_by(date) |>
    dplyr::summarise(xco2_mean=mean(xco2r)) |>
    ggplot2::ggplot(ggplot2::aes(x=date,y=xco2_mean )) +
    ggplot2::geom_point(shape=21,color="black",fill="gray") +
    ggplot2::geom_line(color="red") +
    ggplot2::geom_smooth(method = "lm") +
    ggpubr::stat_regline_equation(ggplot2::aes(
      label =  paste(..eq.label.., ..rr.label.., sep = "*plain(\",\")~~"))) +
    ggplot2::theme_bw()+
    ggplot2::xlab('Date')+
    ggplot2::ylab(expression(
      'Xco'[2][R]~' (ppm)'
    ))
  print(plot_2)
  
  
  ### XCO2 regionalized
  xco2detrend <- xco2df_filter |>
    dplyr::mutate(
      x=1:dplyr::n(),
      xco2_est = mod$coefficients[1] + mod$coefficients[2]*x,
      delta=xco2_est - xco2_mean,
      xco2r = (mod$coefficients[1]-delta)-(mean(xco2_mean)-mod$coefficients[1])
    )
  xco2_aux_detrend <- xco2detrend |>
    dplyr::ungroup() |>
    dplyr::group_by(date) |>
    dplyr::summarise(
      xco2 = mean(xco2r)
    )
  
  ## general linear model
  mod_detrend <- lm(xco2 ~date,
                    data = xco2_aux_detrend )
  beta_r <-mod_detrend$coefficients[2] # regional beta
  ep <- summary(mod_detrend)$coefficients[2,2] # regional standard error
  
  ilbr <- beta_r-ep
  slbr <- beta_r+ep
  
  
  ### creating a nest object by grid cell
  xco2_nest <- xco2detrend |>
    tibble::as_tibble() |>
    dplyr::mutate(year =lubridate::year(date),
                  quarter = lubridate::quarter(date),
                  quarter_year = lubridate::make_date(year, quarter, 1)) |>
    dplyr::group_by(lon, lat,date) |>
    dplyr::summarise(xco2 = mean(xco2r, na.rm=TRUE)) |>
    dplyr::mutate(
      id_time = date
    ) |>
    dplyr::group_by(lon,lat) |>
    tidyr::nest()
  
  ### linear regression for each grid cell
  
  xco2_nest_detrend <- xco2_nest|>
    dplyr::mutate(
      beta_line = purrr::map(data,linear_reg, output="beta1"),
      p_value = purrr::map(data,linear_reg, output="p_value"),
      n_obs = purrr::map(data,linear_reg, output="n"),
      beta_error=purrr::map(data,linear_reg,output='betaerror'),
      model_error=purrr::map(data,linear_reg,output='modelerror')
    )
  
  ### creating a table
  
  xco2_aux_detrend_new <- xco2_nest_detrend |>
    dplyr::filter(n_obs > 4) |> ## criteria of minimum observation month for grid cell
    tidyr::unnest(cols = c(beta_line,beta_error,model_error)) |>
    dplyr::ungroup() |>
    dplyr::select(lon, lat, beta_line,beta_error,model_error)
  
  q3_xco2 <- xco2_aux_detrend_new |> dplyr::pull(beta_line) |> quantile(.75)
  q1_xco2 <- xco2_aux_detrend_new |> dplyr::pull(beta_line) |> quantile(.25)
  
  
  plot3 <- xco2_aux_detrend_new |>
    ggplot2::ggplot(ggplot2::aes(x=beta_line)) +
    ggplot2::geom_histogram(bins=30,
                            fill="orange",
                            color="black") +
    ggplot2::labs(x="βpixel",y="Count") +
    ggplot2::geom_vline(xintercept = q1_xco2,
                        color = "red",
                        lty=2) +
    ggplot2::geom_vline(xintercept = q3_xco2,
                        color = "red",
                        lty=2)+
    gghighlight::gghighlight(beta_line < q1_xco2 | beta_line>q3_xco2,
                             unhighlighted_params = list(
                               color = "darkgray",
                               fill = "lightgray")) +
    ggplot2::theme_minimal()
  print("----------------------------")
  print("significant βpixel histogram")
  print(plot3)
  
  plot4 <- south_america |>
    ggplot2::ggplot()+
    ggspatial::annotation_map_tile(type = 'cartolight')+
    ggplot2::geom_sf(col='grey',fill='white')+
    ggplot2::geom_sf(data=br,col='red',fill='NA')+
    ggplot2::ylim(-35,5.5)+
    ggplot2::xlim(-75,-35)+
    ggplot2::geom_tile(data=xco2_aux_detrend_new |>
                         dplyr::mutate(
                           xco2 = dplyr::case_when(
                             beta_line > q3_xco2 ~ 'Source',
                             beta_line < q1_xco2 ~'Sink',
                             .default = 'Non Significant'
                           )
                         ) |>
                         dplyr::filter(xco2!='Non Significant'),
                       ggplot2::aes(x=lon,y=lat,color=xco2,fill=xco2),
    )+
    map_theme_2()+
    ggplot2::scale_color_manual(values = c('darkgreen','darkred'))+
    ggplot2::scale_fill_manual(values = c('darkgreen','darkred'))+
    ggplot2::labs(x='Longitude',y='Latitude',
                  col=expression('Xco'[2]),fill=expression('Xco'[2]))
  print("----------------------------")
  print("significant source and sink")
  print(plot4)
  
  #### CO2 emission and assimilation
  
  plot5 <- south_america |>
    ggplot2::ggplot()+
    ggspatial::annotation_map_tile(type = 'cartolight')+
    ggplot2::geom_sf(col='grey',fill='white')+
    ggplot2::geom_sf(data=br,col='red',fill='NA')+
    ggplot2::ylim(-35,5.5)+
    ggplot2::xlim(-75,-35)+
    ggplot2::geom_tile(data=xco2_aux_detrend_new |>
                         dplyr::mutate(
                           xco2 = dplyr::case_when(
                             beta_line > q3_xco2 ~ 'Source',
                             beta_line < q1_xco2 ~'Sink',
                             .default = 'Non Significant'
                           )
                         ) |>
                         dplyr::filter(xco2!='Non Significant') |>
                         dplyr::mutate(
                           beta_molm=(beta_line*10000)*44/24.45, # beta conversion to mg mol/m3 day * 10000m ===> mg mol / m2 day
                           fco2 = beta_molm*30/1000, # montly fco2 ===> /1000 is to get in grams
                         ),
                       ggplot2::aes(x=lon,y=lat,color=fco2,fill=fco2)
    )+
    ggplot2::scale_color_gradient(high='yellow',low='blue')+
    ggplot2::scale_fill_gradient(high='yellow',low='blue')+
    map_theme_2()+
    ggplot2::labs(x='Longitude',y='Latitude',
                  col=expression('FCO'[2]~'(g'~m^-2*month^-1~')'),
                  fill=expression('FCO'[2]~'(g'~m^-2*month^-1~')')
    )
  print("----------------------------")
  print("CO2 Flux")
  print(plot5)
  
  plot6 <- south_america |>
    ggplot2::ggplot()+
    ggspatial::annotation_map_tile(type = 'cartolight')+
    ggplot2::geom_sf(col='grey',fill='white')+
    ggplot2::geom_sf(data=br,col='red',fill='NA')+
    ggplot2::ylim(-35,6)+
    ggplot2::xlim(-75,-35)+
    ggplot2::geom_tile(data=xco2_aux_detrend_new |>
                         dplyr::mutate(
                           xco2 = dplyr::case_when(
                             beta_line > q3_xco2 ~ 'Source',
                             beta_line < q1_xco2 ~'Sink',
                             .default = 'Non Significant'
                           )
                         ) |>
                         dplyr::filter(xco2!='Non Significant')|>
                         dplyr::mutate(
                           beta_molm=(beta_error*10000)*44/24.45,
                           fco2_error = beta_molm*30/1000),
                       ggplot2::aes(x=lon,y=lat,color=fco2_error,fill=fco2_error)
    )+
    ggplot2::scale_color_gradient(high='yellow',low='blue')+
    ggplot2::scale_fill_gradient(high='yellow',low='blue')+
    map_theme_2()+
    ggplot2::labs(x='Longitude',y='Latitude',
                  col=expression('FCO'[2]~'error (g'~m^-2*month^-1~')'),
                  fill=expression('FCO'[2]~'error (g'~m^-2*month^-1~')')
    )
  print("----------------------------")
  print("CO2 Flux error")
  print(plot6)
  
  print("===============================================")
  
}

```


